export enum QuantityType {
    Milliliter = 'milliliter',
    Liter = 'liter',
    Deciliter = 'deciliter',
    Teaspoon = 'teaspoon',
    Tablespoon = 'tablespoon',
    FluidOunce = 'fluid ounce',
    Gill = 'gill',
    Cup = 'cup',
    Pint = 'pint',
    Quart = 'quart',
    Gallon = 'gallon',
    Milligram = 'milligram',
    Gram = 'gram',
    Kilogram = 'kilogram',
    Pound = 'pound',
    Ounce = 'ounce',
    Millimeter = 'millimeter',
    Centimeter = 'centimeter',
    Meter = 'meter',
}